### PR TITLE
Beginning of a French translation

### PR DESCRIPTION
**Pull request by samueltardieu**
Here is the beginning of a French translation.

More efforts will be needed to localize the com.magdag.agit.util.Time class, as you will have to do pattern substitutions ("%d days ago" -> "il y a %d jours") which have to be done with a Context around.

### CODE REVIEW

**Comment by rtyley** [comment]
Thanks Samuel, that's fantastic work - I'll take a proper look at it tonight.

**Comment by rtyley** [comment]
Just checked it out, looks great - if you're ok with the contribution terms at https://github.com/rtyley/agit/wiki/Contributing I'll be happy to merge this request - will also look at updating Time.java

**Comment by samueltardieu** [comment]
Those changes are trivial enough, I therefore place them into the public domain.

**Comment by rtyley** [comment]
Brilliant - thank you!

**Pull request merged**
